ilayda-the-Disc0Queen/Exhibitz

- app/models/exhibit.rb
- app/models/museum.rb
- db/migrate/20200525145615_create_exhibits.rb
- db/migrate/20200525150158_create_museums.rb
- db/schema.rb
- test/models/exhibit_test.rb
- test/models/museum_test.rb
without it's foreign key to the exhibit model
> Adding museum model

- app/models/artist.rb
- app/models/booking.rb
- app/models/exhibit.rb
- app/models/exhibit_artist.rb
- app/models/favourite.rb
- app/models/user.rb
- db/migrate/20200525151941_add_museum_to_exhibits.rb
- db/migrate/20200525152402_create_join_table_exhibit_artist.rb
- db/migrate/20200525165337_create_favourites.rb
- db/migrate/20200525170120_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/exhibit_artist_test.rb
- test/models/favourite_test.rb
Added Favourites and Booking models and and sorted out the associations for their join tables
> Adding foreign keys

- app/controllers/artists_controller.rb
- app/controllers/exhibits_controller.rb
- app/controllers/museums_controller.rb
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- app/views/exhibits/index.html.erb
- app/views/exhibits/show.html.erb
- app/views/museums/index.html.erb
- app/views/museums/show.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- test/controllers/artists_controller_test.rb
- test/controllers/exhibits_controller_test.rb
- test/controllers/museums_controller_test.rb
controller and views are created, check it please
> Controllers and views are created

- db/seeds.rb
> Testing seeds

- db/seeds.rb
Added the museums, exhibitions, artists, please check it
> Museums, exhibitions, artists created

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/exhibits/index.html.erb
- app/views/layouts/application.html.erb
> Added banner, header, footer

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_info_card.scss
- app/views/artists/show.html.erb
- app/views/exhibits/show.html.erb
- db/seeds.rb
added links to the bottom artist section of the exhibits show page, and some style components
> Artist show

- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
Added a second navbar, please check it
> Added a second navbar

- app/assets/stylesheets/components/_info_card.scss
- app/views/artists/show.html.erb
> added card to artist show page with image on left and info on right

- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/exhibits/index.html.erb
Made some changes around the layout, added some content, please check it.
> Changed the layout, added extra content

- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/exhibits/index.html.erb
Did some styling around the cards, please check it
> Changed the display of the cards

- app/views/exhibits/index.html.erb
fixed the links on the index page, please check it
> fixed the links

- app/views/layouts/application.html.erb
> linked location map page to navbar

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/show.html.erb
changed the layout, please check it
> changed the layout

- app/views/museums/index.html.erb
fixed museum image links, check it please
> fixed museum image links

- app/assets/stylesheets/pages/_museum-show.scss
- app/views/museums/show.html.erb
did some frontend changes, please check it
> did some frontend changes

- app/views/exhibits/show.html.erb
> fixed descripton but image tag doesn't work for exhbit show page

- app/views/exhibits/show.html.erb
fixed the museum link, check it please
> fixed the museum link

- app/controllers/bookings_controller.rb
- app/views/exhibits/show.html.erb
- db/migrate/20200601102417_add_card_details_to_booking.rb
- db/migrate/20200601110101_add_number_of_tickets_to_bookings.rb
- db/schema.rb
created a payment form, please check it
> created a payment form

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_museumsindex.scss
Changed the font and the banners, please check them
> Changed the font and the banners

- app/controllers/bookings_controller.rb
- app/views/bookings/error.js.erb
- app/views/exhibits/show.html.erb
- db/migrate/20200601152907_change_expiry_date_to_be_date_in_bookings.rb
- db/schema.rb
Bookings schema changed, expiry_date changed to date 
More validation added
> more validation added to the booking modal

- app/assets/stylesheets/pages/_my-bookings.scss
Now all the exhibits content is shown inside the div
> cards resized

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/show.html.erb
changed the layout of the exhibit show page, please check it
> changed the layout of the exhibit show page

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/index.html.erb
- app/views/exhibits/show.html.erb
changed some styling, please check it
> changed some styling

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/_artistshow.scss
- app/assets/stylesheets/pages/_artistsindex.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/artists/show.html.erb
changed the layout and the colors, please check it
> changed the layout and the colors

- app/assets/stylesheets/pages/_museum-show.scss
- app/assets/stylesheets/pages/_my-bookings.scss
- app/views/museums/show.html.erb
changed the text shadow, size of the details box, check it please
> changed the text shadow, size of the details box

- app/assets/stylesheets/pages/_artistsindex.scss
- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/show.html.erb
Book button on exhibit show only appears if isn't a free exhibit.
Shadow on banners h1 is fixed
> validation for free exhibitions. Shadow on banners

- app/assets/stylesheets/pages/_exhibitsindex.scss
- app/assets/stylesheets/pages/_my-bookings.scss
fixed the text shadows, please check it
> fixed the text shadows

- db/seeds.rb
> delete all favoutites when starting to run the seed file

- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/exhibits_controller.rb
removed the login from the main page, please check it
> removed the login from the main page

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_museum-show.scss
changed the font, please check it
> changed the font

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/exhibits/show.html.erb
> changed the format of exhibits show page slightly, and added museum pic

- app/controllers/artists_controller.rb
- app/controllers/museums_controller.rb
deleted authentication from museum index and atrist show, please check it
> deleted authentication from museum index and atrist show

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/show.html.erb
- app/views/layouts/application.html.erb
changed the background color, size of the box, check it please
> changed the background color, size of the box

- app/assets/stylesheets/pages/_museumsindex.scss
- app/views/museums/index.html.erb
changed the padding and adding truncate, check it
> changed the padding and adding truncate

- app/assets/stylesheets/pages/_exhibitsshow.scss
- app/views/exhibits/show.html.erb
layout changes, please check it
> layout changes

- app/views/exhibits/show.html.erb
changed the h3s to h4, please check it
> changed the h3s to h4

- app/assets/stylesheets/pages/_booking-confirmation.scss
- app/assets/stylesheets/pages/_my-bookings.scss
fixed styling, please check it
> fixed styling

- app/assets/stylesheets/pages/_artistshow.scss
- app/views/artists/show.html.erb
hover text colour changed in artist show.
> text color on hover changed

- app/views/layouts/application.html.erb
linked twitter and linkedin, please check it
> linked twitter and linkedin

- app/assets/stylesheets/pages/_my-bookings.scss
- app/views/bookings/index.html.erb
fixed typo and padding, please check it
> fixed typo and padding

- app/views/bookings/confirmation.html.erb
- app/views/bookings/index.html.erb
changed the order of the date, please check it
> changed the order of the date
